config: |-
  #operator.charts.values.storage.shared.storageClassName=nfs
  #operator.charts.values.storage.default.storageClassName=standard

  #operator.charts.values.resources.cpu.defaultRequests=0.2
  #operator.charts.values.resources.memory.defaultRequests=512Mi
