{{ if $.Values.backup.enabled }}
# Setup extra config that is mapped to the container
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "60"
    {{ $.Values.annotationKeys.neverOverwrite }}: true
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  config.yaml: |
    # Basic backup parameters
    backup:
      enabled: {{ $.Values.backup.agent.enabled }}
      schedule: {{ $.Values.backup.agent.schedule | quote }}
    
    restic:
      env:
        restic_repository: {{ $.Values.backup.agent.restic_repo_prefix }}/{{ $.Values.deployment.namespace }}
        restic_password: unset
{{- end }}
