apiVersion: v1
name: xp-operator
version: 0.18
appVersion: 0.18
home: https://github.com/enonic/xp-operator
description: Enonic XP Kubernetes operator
sources:
  - https://github.com/enonic/xp-operator
maintainers:
  - name: Guðmundur Björn Birkisson (gbi@enonic.com)
