apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: xp7configs.enonic.cloud
spec:
  group: enonic.cloud
  scope: Namespaced
  preserveUnknownFields: false
  names:
    kind: Xp7Config
    singular: xp7config
    plural: xp7configs
  versions:
    - name: v1alpha2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                nodeGroup:
                  type: string
                file:
                  type: string
                data:
                  type: string
                dataBase64:
                  type: boolean
                  nullable: true
            status:
              type: object
              nullable: true
              properties:
                state:
                  type: string
                  enum: ["ERROR", "PENDING", "READY"]
                message:
                  type: string
      additionalPrinterColumns:
        - name: NodeGroup
          type: string
          description: Node running the config
          jsonPath: .spec.nodeGroup
        - name: File
          type: string
          description: Config file name
          jsonPath: .spec.file
        - name: State
          type: string
          description: State
          jsonPath: .status.state
        - name: Msg
          type: string
          description: Message
          jsonPath: .status.message